### ISSUE TITLE
Lookup table for the tags (English)

### ISSUE THREAD

**Issue by FahdCodes** [UCREL/pymusas#33]
Hi,

For the USAS tags like 'A11.1+', 'N3.2+', 'Z1mf', 'Z3c' etc, is there a lookup table to get the corresponding English name of the tags?

Thanks!
Fahad

**Comment by perayson** [comment]
Hi Fahad, yes indeed. 

See the various formats linked from https://ucrel.lancs.ac.uk/usas/ e.g. https://ucrel.lancs.ac.uk/usas/semtags.txt or https://ucrel.lancs.ac.uk/usas/USASSemanticTagset.pdf or https://ucrel.lancs.ac.uk/usas/semtags_subcategories.txt for English. Other language versions are available on https://github.com/UCREL/Multilingual-USAS 

Paul.
