### ISSUE TITLE
issue loading "en_dual_none_contextual"

### ISSUE THREAD

**Issue by jasp9559** [UCREL/pymusas#35]
I am Jaspreet and am using the code from URCEL under your repository for a project of mine. I was trying to implement the code for English language and the following error for 'en_dual_none_contextual" is coming repeatedly. I am not sure why?  Could you please help out on this. 
![image](https://user-images.githubusercontent.com/82469151/186328337-8a0f82a8-6f67-438c-9f05-3e046b35c281.png)

Kindly help out on this AEAP

Regards

Jaspreet Singh

**Comment by perayson** [comment]
Thanks for flagging this @jasp9559, can you confirm which version of spaCy you are using? I wonder if you need to fix to v3.3.1 as described here: https://github.com/UCREL/pymusas/issues/34 in an earlier issue?

**Comment by jasp9559** [comment]
Ok will check and come back, thanks for the reply

**Comment by perayson** [comment]
Now resolved with this recent update: https://github.com/UCREL/pymusas-models/pull/5
